package sop_corba;


/**
* sop_corba/ObtenerEstadisticasInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* lunes 3 de julio de 2023 08:15:15 AM COT
*/

public interface ObtenerEstadisticasInt extends ObtenerEstadisticasIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ObtenerEstadisticasInt
