package sop_corba.ObtenerEstadisticasIntPackage;


/**
* sop_corba/ObtenerEstadisticasIntPackage/ultimasOfertasDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* lunes 3 de julio de 2023 04:15:01 PM COT
*/

public final class ultimasOfertasDTO implements org.omg.CORBA.portable.IDLEntity
{
  public float ultimasOfertas[] = null;

  public ultimasOfertasDTO ()
  {
  } // ctor

  public ultimasOfertasDTO (float[] _ultimasOfertas)
  {
    ultimasOfertas = _ultimasOfertas;
  } // ctor

} // class ultimasOfertasDTO
