package sop_corba.ObtenerEstadisticasIntPackage;


/**
* sop_corba/ObtenerEstadisticasIntPackage/ultimasOfertasDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* lunes 3 de julio de 2023 04:15:01 PM COT
*/

abstract public class ultimasOfertasDTOHelper
{
  private static String  _id = "IDL:sop_corba/ObtenerEstadisticasInt/ultimasOfertasDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.ObtenerEstadisticasIntPackage.ultimasOfertasDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.ObtenerEstadisticasIntPackage.ultimasOfertasDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (sop_corba.ObtenerEstadisticasIntPackage.float_seqHelper.id (), "float_seq", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "ultimasOfertas",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.ObtenerEstadisticasIntPackage.ultimasOfertasDTOHelper.id (), "ultimasOfertasDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.ObtenerEstadisticasIntPackage.ultimasOfertasDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.ObtenerEstadisticasIntPackage.ultimasOfertasDTO value = new sop_corba.ObtenerEstadisticasIntPackage.ultimasOfertasDTO ();
    value.ultimasOfertas = sop_corba.ObtenerEstadisticasIntPackage.float_seqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.ObtenerEstadisticasIntPackage.ultimasOfertasDTO value)
  {
    sop_corba.ObtenerEstadisticasIntPackage.float_seqHelper.write (ostream, value.ultimasOfertas);
  }

}
